### ISSUE TITLE
Not Python 3

### ISSUE THREAD

**Issue by druck13** [gerph/riscos-filer-python#1]
3 uses of `isinstance(xxx, (str, unicode)` incompatible with Python 3

**Comment by gerph** [comment]
Mutter... it should be Python 2/3 compatible, so I failed there. This will be fixed :-)

**Comment by gerph** [comment]
Working now, with sha eac602888ca43898e90d8ab0e84b999b811c5f81.

![image](https://user-images.githubusercontent.com/13813876/227062225-97c166f5-26b4-4ebc-abb1-aa6b5274371e.png)

**Comment by gerph** [comment]
Thanks for the report. Hopefully this is enough to make it compatible to Python 3.
